{
 "title": "api calls metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Min/max latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API min latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_min\r\n  [5m]\r\n))\r\n"
    }
   ]
  },
  {
   "title": "API calls max latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_max\r\n  [5m]\r\n))"
    }
   ]
  },
  { "title": "Percentile latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "API calls p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_95_percentile\r\n  [5m]\r\n))\r\n"
    }
   ]
  },
  {
   "title": "API calls p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_99_percentile\r\n  [5m]\r\n))\r\n"
    }
   ]
  },
  { "title": "Median/mean latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "API calls latency median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_median\r\n  [5m]\r\n))"
    }
   ]
  },
  {
   "title": "API calls latency mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_mean\r\n  [5m]\r\n))"
    }
   ]
  }
 ]
}