{
 "title": "api calls metrics",
 "time": { "from": "2026-07-14T23:00:00.000Z", "to": "2026-07-25T22:59:59.000Z" },
 "panels": [
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_description=\"Time for entire data check process\"\r\n  | unwrap message_duration\r\n  [$__interval]\r\n)"
    }
   ]
  },
  { "title": "Min/max latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "API min latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_min\r\n  [5m]\r\n))\r\n"
    }
   ]
  },
  {
   "title": "API calls max latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_max\r\n  [5m]\r\n))"
    }
   ]
  },
  { "title": "Percentile latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "API calls p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_95_percentile\r\n  [5m]\r\n))\r\n"
    }
   ]
  },
  {
   "title": "API calls p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_99_percentile\r\n  [5m]\r\n))\r\n"
    }
   ]
  },
  { "title": "Median/mean latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "API calls latency median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_median\r\n  [5m]\r\n))"
    }
   ]
  },
  {
   "title": "API calls latency mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\r\n  {job=\"my_app\"}\r\n  | json\r\n  | message_operation_type=\"input_feature_creation\"\r\n  | unwrap message_feature_api_calls_latency_mean\r\n  [5m]\r\n))"
    }
   ]
  }
 ]
}