import numpy as np

def calculate_accuracy(classifier, predictions, X_test, y_test, N=5):
  wrongPredictions=[]  
  correct_predictions=0
  correct_prediction_in_top_N_results=0
  for j, pred in enumerate(predictions):
     top_N_results_indices = np.argsort(pred)[-N:]
     top_N_results = classifier.classes_[top_N_results_indices]
     if top_N_results[-1] == y_test[j]:
         correct_predictions = correct_predictions + 1
     print([x for x in top_N_results])
     if y_test[j] in top_N_results:
         correct_prediction_in_top_N_results+=1
     else:
         wrongPredictions.append({"TopNPredictions": list(top_N_results), "True": list(y_test[j])[0]})
  print(f"Accuracy: {correct_predictions/len(predictions)}.")
  print(f"Correct or in top {N} results:{correct_prediction_in_top_N_results/len(predictions)}")
  return wrongPredictions

def set_value_with_dtype(df, column, index, value_str):
    dtype = df[column].dtype
    try:
        # Convert string to the column's dtype
        if pd.api.types.is_integer_dtype(dtype):
            value = int(value_str)
        elif pd.api.types.is_float_dtype(dtype):
            value = float(value_str)
        elif pd.api.types.is_bool_dtype(dtype):
            value = value_str.lower() in ["true", "1", "yes"]
        elif pd.api.types.is_datetime64_any_dtype(dtype):
            value = pd.to_datetime(value_str)
        else:
            # Treat as string/object
            value = value_str
        df.loc[index, column] = value
    except Exception as e:
        raise ValueError(f"Could not convert '{value_str}' to {dtype}") from e

def obtain_correct_data_labels(data_with_predictions, explanation_of_prediction, target_label):
    data_with_updated_predictions=data_with_predictions.copy()
    print("We will now determine if the predictions returned by a model are correct.")
    # Show explanation of input data/predictions generated by a model...
    print(explanation_of_prediction)
    for index, sample in data_with_updated_predictions.iterrows():
        print(f"Sample {index}")
        print(sample)
        input_prompt = "For this sample, the model predicted: {sample[target_label]}. Is this correct? y/n "
        isPredictionCorrect = input(input_prompt)
        if isPredictionCorrect == "n":
            changePrediction = input("Do you want to provide the correct value for this prediction? y/n ")
            if changePrediction == "y":
                correctPrediction = input("What is the correct value for this prediction? ")
                # we need to check if the datatype for prediction is right
                set_value_with_dtype(data_with_updated_predictions, target_label, index, correctPrediction)
    return data_with_updated_predictions

