import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from xgboost import XGBClassifier
from src.ml_resources import save_versioned_pickle_file
import logging
from src.logging.utility import StructuredMessage, setup_logging

#logger=setup_logging()

def calculate_accuracy(classifier, predictions, X_test, y_test, N=5):
  wrongPredictions=[]  
  correct_predictions=0
  correct_prediction_in_top_N_results=0
  correct_l1_predictions=0
  correct_l1_in_top_N=0
  for j, pred in enumerate(predictions):
     top_N_results_indices = np.argsort(pred)[-N:]
     top_N_results = classifier.classes_[top_N_results_indices]
     if top_N_results[-1] == y_test[j]:
         correct_predictions = correct_predictions + 1
     #print(str(y_test[j]))
     if not isinstance(classifier, XGBClassifier) and top_N_results[-1][0:3] == str(y_test[j])[0:3]:
         correct_l1_predictions = correct_l1_predictions + 1
     #print([x for x in top_N_results])
     #print(y_test[j])
     if not isinstance(classifier, XGBClassifier) and y_test[j][0:3] in [x[0:3] for x in top_N_results]:
         correct_l1_in_top_N+=1
     if y_test[j] in [x for x in top_N_results]:
         correct_prediction_in_top_N_results+=1
     else:
        wrongPredictions.append({"TopNPredictions": list(top_N_results), "True": y_test[j]})
  print(f"Accuracy: {correct_predictions/len(predictions)}.")
  print(f"Correct or in top {N} results:{correct_prediction_in_top_N_results/len(predictions)}")
  print(f"L1 correct: {correct_l1_predictions/len(predictions)}")
  print(f"L1 in top N L1: {correct_l1_in_top_N/len(predictions)}")
  return  {"Accuracy": correct_predictions/len(predictions),
           "N": N,
           "TopNAccuracy": correct_prediction_in_top_N_results/len(predictions),
           "L1Correct": correct_l1_predictions/len(predictions),    
           "TopNAccuracyL1": correct_l1_in_top_N/len(predictions), 
           "WrongPredictions": wrongPredictions}

def set_value_with_dtype(df, column, index, value_str):
    dtype = df[column].dtype
    try:
        # Convert string to the column's dtype
        if pd.api.types.is_integer_dtype(dtype):
            value = int(value_str)
        elif pd.api.types.is_float_dtype(dtype):
            value = float(value_str)
        elif pd.api.types.is_bool_dtype(dtype):
            value = value_str.lower() in ["true", "1", "yes"]
        elif pd.api.types.is_datetime64_any_dtype(dtype):
            value = pd.to_datetime(value_str)
        else:
            # Treat as string/object
            value = value_str
        df.loc[index, column] = value
    except Exception as e:
        raise ValueError(f"Could not convert '{value_str}' to {dtype}") from e

def measure_prediction_accuracy(data_with_predictions):
    reports={}
    for item_type in data_with_predictions.keys():
        data_with_predictions[item_type]['modelInput']['Flagged']=data_with_predictions[item_type]['predictions']
        y_true=[]
        ground_truth=""
        for index, item in data_with_predictions[item_type]['modelInput'].iterrows():
            print(item)
            print(index)
            while ground_truth not in ['y', 'n']:
                ground_truth=input("Is this right? y/n")
            if ground_truth=='y':
                y_true.append(item['Flagged'])
            elif item['Flagged']==1:
                y_true.append(-1)
            else:
                y_true.append(1)
            ground_truth=""
        reports[item_type] = classification_report(y_true,
            data_with_predictions[item_type]['predictions'],
            output_dict=True
            )    
    return reports

def obtain_correctly_labelled_data(data_with_predictions,
    explanation_of_prediction,
    target_label,
    model_name_version,
    training_data,
    df_relationships_unique,
    df_relationships,
    item_type="items",
    target_variable_is_binary=False,
    reports_directory='./projects/am2_project/experiments/',
    generate_classification_report=False,
    only_relabel_outliers=True,
    categories=[0,1],
    all_reports={}):
    #print(data_with_predictions)
    number_of_outliers=len(data_with_predictions[data_with_predictions['Flagged']==-1])
    print(f"The number of items in IsolationForest input: {len(data_with_predictions)}")
    print(f"The number of outliers: {number_of_outliers}")
    user_labelled_data=data_with_predictions.copy()
    #logger = logging.getLogger("am2_project")
    print("We will now determine if the predictions returned by a model are correct.")
    # Show explanation of input data/predictions generated by a model...
    print(explanation_of_prediction)
    #print(list(set(data_with_predictions['Flagged'])))
    count=1
    for index, sample in user_labelled_data.iterrows():
        if (only_relabel_outliers==False or (only_relabel_outliers==True and sample[target_label]==-1)):
            print(f"Sample {index}")
            print(sample)
            for i,val in sample.items():
                if i in df_relationships.columns:
                    num_instances=len([x2 for x2 in (df_relationships[i]==val).values.tolist() if x2==True])
                    num_not_instances=len(df_relationships)
                    print(f"Number of {i} with value {val} in the data: {num_instances}, {num_instances/num_not_instances}")
            matched = df_relationships[(df_relationships == df_relationships_unique.loc[index]).all(axis=1)]
            print("Progress: ")
            if only_relabel_outliers==True:
                print(f"{count} of {number_of_outliers}")
            else:
                print(f"{count} of {len(data_with_predictions)}")
            count=count+1
            input_prompt = f"For the {len(matched)}/{len(df_relationships)} samples identical to this, the model predicted: {sample[target_label]}. Is this correct? y/n "
            isPredictionCorrect = input(input_prompt)
            reasons_for_anomaly_labels=["Not rendering on portal",
                    "Incorrect API results",
                    "Missing relationship"]
            reason_for_anomaly=""
            type_of_missing_related_item=""
            if isPredictionCorrect != "y":
                print("CORRECT PREDICTION")
                if target_variable_is_binary:
                    # Because the target variable is binary, we don't need to ask the user to
                    # specify the correct value
                    if sample[target_label]==categories[0]:
                        correct_prediction=categories[1]
                    else:
                        correct_prediction=categories[0]
                else:
                    correct_prediction = ""
                    ##changePrediction = input(f"Do you want to provide the correct value for this prediction? {("", "Correct prediction:")[len("") == 0]} {correct_prediction} y/n ")
                    changePrediction = input("Provide correct value?")
                    if changePrediction == "y":
                        if not target_variable_is_binary:
                            correctPrediction = input(f"What is the correct value for this prediction? {correct_prediction}")
                # we need to check if the datatype for prediction is right
                set_value_with_dtype(user_labelled_data, target_label, index, correct_prediction)
            if (explanation_of_prediction=='We are correcting the pseudo-labelled datasets created with isolation forests'
                and ((sample[target_label]==-1 and isPredictionCorrect == "y") or
                (sample[target_label]==1 and isPredictionCorrect == "n"))):
                reason_for_anomaly=0
                while reason_for_anomaly not in ["1","2","3"]:
                    reason_for_anomaly=input("""Why do you think this outlier is anomalous?
                            1. Item is not rendering correctly on Discovery portal
                            2. REST API queries involving this item delivering unexpected results
                            3. Item is not referencing/referenced by another item that it should
                            """)
                if reason_for_anomaly=="3":
                    type_of_missing_related_item=input("What type of item is missing from the relationships? ")
                if only_relabel_outliers==True:
                    logger.info(StructuredMessage(message=f"Outlier confirmed as anomalous by human",
                            operation_type="anomaly_confirmation",
                            item_id=index,
                            item_type=item_type,
                            all_similar_items=matched.index.tolist(),
                            anomaly_detection_correct=isPredictionCorrect,
                            reason_for_anomaly=reasons_for_anomaly_labels[int(reason_for_anomaly)-1],
                            type_of_missing_related_item=type_of_missing_related_item.lower()
                        ))
    target_values=[str(x) for x in set(user_labelled_data['Flagged']) | set(data_with_predictions['Flagged'])]
    report = classification_report(user_labelled_data['Flagged'],
        data_with_predictions['Flagged'],
        #target names aren't being set correctly, leave this in for now, might
        # need it in future
        #target_names=target_values,
        output_dict=True
        )
    print("y_true")   
    print([int(x) for x in list(user_labelled_data['Flagged'].values)])
    print("y_pred")
    print([int(x) for x in list(data_with_predictions['Flagged'].values)])
    print(report)
    report_dict = classification_report(user_labelled_data['Flagged'],
            data_with_predictions['Flagged'],
            #target_names=target_values,
            output_dict=True)
    all_reports[item_type]=report_dict
    if generate_classification_report:
        indices_flagged = [i for i, x in enumerate(data_with_predictions['Flagged']) if x == -1]
        notes_on_experiment = input("Enter any notes on this experiment you wish to record (e.g. parameters, evaluation metrics, what did/didn't work): ")
        with open(f"{reports_directory}classification_report_{model_name_version}.txt", "w") as f:
            _ = f.write(f"Classification report for {item_type}\n\n")
            _ = f.write(f"Notes: \n{notes_on_experiment}\n\n")
            _ = f.write(f"Model name and version: \n{model_name_version}\n\n")
            _ = f.write(f"Training data: \n{training_data}\n\n")
            _ = f.write(f"Classification report: \n{report}\n\n")
            _ = f.write("These items have been flagged as needing attention.\n\n")
            for index_flagged in indices_flagged:
                _ = f.write(f"{data_with_predictions.index[index_flagged]}\n")
    print(f"\n\nFinished {item_type}")
    return {"UserLabelledData": user_labelled_data,
            "ResultsReport": report_dict}

            