import numpy as np
from sklearn.metrics import classification_report

def calculate_accuracy(classifier, predictions, X_test, y_test, N=5):
  wrongPredictions=[]  
  correct_predictions=0
  correct_prediction_in_top_N_results=0
  for j, pred in enumerate(predictions):
     top_N_results_indices = np.argsort(pred)[-N:]
     top_N_results = classifier.classes_[top_N_results_indices]
     if top_N_results[-1] == y_test[j]:
         correct_predictions = correct_predictions + 1
     print([x for x in top_N_results])
     if y_test[j] in top_N_results:
         correct_prediction_in_top_N_results+=1
     else:
         wrongPredictions.append({"TopNPredictions": list(top_N_results), "True": list(y_test[j])[0]})
  print(f"Accuracy: {correct_predictions/len(predictions)}.")
  print(f"Correct or in top {N} results:{correct_prediction_in_top_N_results/len(predictions)}")
  return wrongPredictions

def set_value_with_dtype(df, column, index, value_str):
    dtype = df[column].dtype
    try:
        # Convert string to the column's dtype
        if pd.api.types.is_integer_dtype(dtype):
            value = int(value_str)
        elif pd.api.types.is_float_dtype(dtype):
            value = float(value_str)
        elif pd.api.types.is_bool_dtype(dtype):
            value = value_str.lower() in ["true", "1", "yes"]
        elif pd.api.types.is_datetime64_any_dtype(dtype):
            value = pd.to_datetime(value_str)
        else:
            # Treat as string/object
            value = value_str
        df.loc[index, column] = value
    except Exception as e:
        raise ValueError(f"Could not convert '{value_str}' to {dtype}") from e

def obtain_correctly_labelled_data(data_with_predictions,
    explanation_of_prediction,
    target_label,
    model_name_version,
    training_data,
    item_type="items",
    target_variable_is_binary=False):
    user_labelled_data=data_with_predictions.copy()
    print("We will now determine if the predictions returned by a model are correct.")
    # Show explanation of input data/predictions generated by a model...
    print(explanation_of_prediction)
    for index, sample in user_labelled_data.iterrows():
        print(f"Sample {index}")
        print(sample)
        input_prompt = f"For this sample, the model predicted: {sample[target_label]}. Is this correct? y/n "
        isPredictionCorrect = input(input_prompt)
        if isPredictionCorrect == "n":
            if target_variable_is_binary:
                    # Because the target variable is binary, we don't need to ask the user to
                    # specify the correct value
                    if sample[target_label]==list(set(data_with_predictions['Flagged']))[0]:
                        correct_prediction=list(set(data_with_predictions['Flagged']))[1]
                    else:
                        correct_prediction=list(set(data_with_predictions['Flagged']))[0]
            else:
                correct_prediction = ""
            changePrediction = input(f"Do you want to provide the correct value for this prediction? {correct_prediction} y/n ")
            if changePrediction == "y":
                if not target_variable_is_binary:
                    correctPrediction = input(f"What is the correct value for this prediction? {correct_prediction}")
                # we need to check if the datatype for prediction is right
                set_value_with_dtype(user_labelled_data, target_label, index, correct_prediction)
    indices_flagged = [i for i, x in enumerate(data_with_predictions['Flagged']) if x == -1]
    target_values=[str(x) for x in set(user_labelled_data['Flagged']) | set(data_with_predictions['Flagged'])]
    report = classification_report(user_labelled_data['Flagged'], data_with_predictions['Flagged'], target_names=target_values)
    print(report)
    notes_on_experiment = input("Enter any notes on this experiment you wish to record (e.g. parameters, evaluation metrics, what did/didn't work): ")
    with open(f"classification_report_{item_type}.txt", "w") as f:
            _ = f.write(f"Classification report for {item_type}\n\n")
            _ = f.write(f"Notes: \n{notes_on_experiment}\n\n")
            _ = f.write(f"Model name and version: \n{model_name_version}\n\n")
            _ = f.write(f"Training data: \n{training_data}\n\n")
            _ = f.write(f"Classification report: \n{report}\n\n")
            _ = f.write("These items have been flagged as needing attention.\n\n")
            for index_flagged in indices_flagged:
                _ = f.write(f"{data_with_predictions.index[index_flagged]}\n")
    print(f"\n\nFinished {item_type}")
    return user_labelled_data